### ISSUE TITLE
Smarter auto-quoting

### ISSUE THREAD

**Issue by jesseleite** [nvim-telescope/telescope-rg.nvim#6]
Firstly, thanks @weeman1337 for taking the time with this extension! Life got busy, and [my PR](https://github.com/nvim-telescope/telescope.nvim/pull/670) fell by the wayside 😂 

Anyway, one of the features I had started to implement in my PR was auto-quoting. For example in your extension, I can't search a string like `function create` unless I wrap it in quotes `'function create'` first.

I personally think spaces should be treated as part of the search query, unless command line options are needed, or quotes are part of the query you are trying to search...

| User's query: | Runs: | Note: |
| :--- | :--- | :--- |
| `function create` | `rg 'function create'` | Quotes not necessary |
| `func.*create` | `rg 'func.*create'` | Quotes not necessary |
| `it's a wonderful life` | `rg "it's a wonderful life"` | If only one quote instead of pair, quotes not necessary |
| `'function create'` | `rg 'function create'` | Don't auto-quote if they explicitly wrap with quotes |
| `"function create"` | `rg "function create"` | Don't auto-quote if they explicitly wrap with quotes |
| `-uu 'func.*create'` | `rg -uu 'func.*create'` | Don't auto-quote if they pass opts/args |
| `'func.*create' vendor` | `rg 'func.*create' vendor` | Don't auto-quote if they pass opts/args |

_Note: The `it's a wonderful life` example might be the most subjective and/or complicated one. The way I had implemented it in https://github.com/jesseleite/vim-agriculture was, if a single quote is used in the query at all, then don't auto-quote anything, and expect the user to wrap the query in quotes. It would be neat if it could detect single quotes vs quote pairs, but I understand if we skip on that one._

Curious on your thoughts? ❤️

**Comment by weeman1337** [comment]
Thanks for the detailed explanation. Currently it is really "raw" because it parses the prompt like shell args.

What about this?:
- quote the entire prompt if not starting with `-`, `'`, `"`
  - Should quotes in between be escaped (e.g. `function "create` → `"function \"create"`)?
- else parse like shell args

Covers everything inlcuding the wonderful life ;)

One common search I am running is `somestring insomedir`. With „smart auto-quoting“ this has to be `"somestring" insomedir`. I would prefer keeping the shell like argument parsing → It should be configurable (enabled by default?).

**Comment by jesseleite** [comment]
> quote the entire prompt if not starting with `-`, `'`, `"`

That sounds great to me!

> It should be configurable (enabled by default?)

Just my two cents, but I do think smart-quoting should be enabled by default personally; No other telescope prompt expects you to quote simple multiple word queries like this...

![image](https://user-images.githubusercontent.com/5187394/142944425-b4df14f9-38ca-4aab-86b3-8af6eb32e4ca.png)

Anyway, appreciate you taking over this feature!

**Comment by weeman1337** [comment]
The auto-quoting can be tested in #13. Also happy for any PR feedback.
