### ISSUE TITLE
`telescope-live-grep-raw.nvim` vs `telescope-rg.nvim`?

### ISSUE THREAD

**Issue by jesseleite** [nvim-telescope/telescope-rg.nvim#8]
I see this repo was renamed from `telescope-live-grep-raw.nvim` to `telescope-rg.nvim`...

Technically, `live_grep_raw` should work with other search tools like `ag` instead of `rg` if the user sets their vimgrep options to suit, right?

Also, if the extension is loaded via `load_extension('live_grep_raw')`, doesn't it make more sense to use that terminology in the repo name as well?

**Comment by weeman1337** [comment]
As far as I understood the idea was building it specifically for `rg`:  
See https://github.com/nvim-telescope/telescope-rg.nvim/issues/5

The README is not up to date. I am going to change this later with #7 .

**Comment by jesseleite** [comment]
Ah sorry, didn't see that convo. Anyway, if the user wants to configure `ag` / [thesilversearcher](https://github.com/ggreer/the_silver_searcher) in their telescope [vimgrep_arguments](https://github.com/nvim-telescope/telescope.nvim/blob/d686fb27998fc130f7b851fb6c540f3f1fe806e8/lua/telescope/config.lua#L538-L559), can they not still use `live_grep_raw`?

**Comment by weeman1337** [comment]
Let's carry the discussion over here: Should it be renamed once again?  
Is it possible naming it `live_grep` at all? Because that collides with `live_grep` in Telescope „core“.

@Conni2461 @tjdevries

**Comment by jesseleite** [comment]
Whoops, it moved again lol. I just commented [over there again](https://github.com/nvim-telescope/telescope-rg.nvim/issues/5#issuecomment-975958662).

**Comment by weeman1337** [comment]
We can name it `live_grep` and move it out with an announcement here #1470 .

**Comment by tjdevries** [comment]
hmmm, I don't know if we need to move live_grep out. This could change to `rg_live` or `live_rg` or something.

I particularly don't want this plugin (telescope-rg) to even consider what would work for other grep services. It complicates everything, obscures easy names, etc. It has been quite annoying to maintain three or more "grep-like" alternatives for various aspects. So don't worry about that in this plugin.

**Comment by jesseleite** [comment]
> I don't know if we need to move live_grep out

Are all the builtins eventually getting moved out, [as per this discussion](https://github.com/nvim-telescope/telescope.nvim/issues/1228)?

> This could change to `rg_live` or `live_rg` or something

@tjdevries Two quick thoughts on this...

1) This extension isn't coupled to `rg`; It's coupled to whatever the user's `vimgrep_arguments` happen to be.

2) What if we rename this repo/extension to `live_grep_args`?

    - If this extension allows the user to `live_grep` with their own `args`, why not `live_grep_args` ? 🙂

    - This would address my concern above about coupling the name to `rg`; Again, both `live_grep` and `live_grep_args` happen to use `rg` by default, but only because of what's in the default `vimgrep_arguments`.

Don't want to die on the hill though. Just my two cents ❤️

**Comment by lobre** [comment]
If vimgrep_arguments are set to something like `rg --files`, it also means this can be used as a `find_files` replacement, adding support to `rg` flags.

Taking that into account, I feel that having `live_grep` in the name would not necessarily make sense neither?

That is just a thought, but effectively the native `live_grep` in telescope can also be configured with `rg --files`. I am wondering what is the technical difference behind the scenes between `live_grep` and `find_files` then (apart from setting the default `rg` flags).

**Comment by weeman1337** [comment]
Coming back to this @Conni2461 should we rename it one last time to `live_grep`? I would then update the code and docs.

**Comment by Conni2461** [comment]
Please not `live_grep` this will be a name clash with current `live_grep`. Off the top of my head i don't know what will prioritized extension or builtin when using `:Telescope`

`live_grep_args` works for me.

**Comment by weeman1337** [comment]
Go `live_grep_args`! :partying_face:

**Comment by Conni2461** [comment]
Do i have to do something?

Want to prep a PR that changes the references inside the repo and i merge and rename at the same time, if you dont have the permissions to rename

Something i am not sure about is that `telescope.load(" ... ")` will change if we change the dir name. This is a breaking change

**Comment by weeman1337** [comment]
> Do i have to do something?

Can you just rename the repo? We did this before. Everything is still working then since GitHub allows clone using previous names.

I will then take care oft the rest. I am planning to display a notice to the users that they should adapt to the new name.
